<?php 
session_start();
id($_SESSION['clientid']!=null){
    $nomeclient=$_SESSION['nomeclient'];
    $clientid=$_SESSION['clientid'];
    $usertype=$_SESSION['usertype'];
}
else{
    header('location:login.html');
}
?>